/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-artikel': RouteRecordInfo<'admin-artikel', '/admin/artikel', Record<never, never>, Record<never, never>>,
    'admin-banner': RouteRecordInfo<'admin-banner', '/admin/banner', Record<never, never>, Record<never, never>>,
    'admin-chats': RouteRecordInfo<'admin-chats', '/admin/chats', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-kategori': RouteRecordInfo<'admin-kategori', '/admin/kategori', Record<never, never>, Record<never, never>>,
    'admin-kupon': RouteRecordInfo<'admin-kupon', '/admin/kupon', Record<never, never>, Record<never, never>>,
    'admin-laporan': RouteRecordInfo<'admin-laporan', '/admin/laporan', Record<never, never>, Record<never, never>>,
    'admin-persetujuan-akun': RouteRecordInfo<'admin-persetujuan-akun', '/admin/persetujuan-akun', Record<never, never>, Record<never, never>>,
    'admin-produk': RouteRecordInfo<'admin-produk', '/admin/produk', Record<never, never>, Record<never, never>>,
    'admin-settings': RouteRecordInfo<'admin-settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    'admin-tickets': RouteRecordInfo<'admin-tickets', '/admin/tickets', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-withdrawals': RouteRecordInfo<'admin-withdrawals', '/admin/withdrawals', Record<never, never>, Record<never, never>>,
    'akun-id': RouteRecordInfo<'akun-id', '/akun/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'blog': RouteRecordInfo<'blog', '/blog', Record<never, never>, Record<never, never>>,
    'blog-slug': RouteRecordInfo<'blog-slug', '/blog/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'game-slug': RouteRecordInfo<'game-slug', '/game/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'invoice-id': RouteRecordInfo<'invoice-id', '/invoice/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'member-chat': RouteRecordInfo<'member-chat', '/member/chat', Record<never, never>, Record<never, never>>,
    'member-chat-id': RouteRecordInfo<'member-chat-id', '/member/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'member-dashboard': RouteRecordInfo<'member-dashboard', '/member/dashboard', Record<never, never>, Record<never, never>>,
    'member-jual-akun': RouteRecordInfo<'member-jual-akun', '/member/jual-akun', Record<never, never>, Record<never, never>>,
    'member-referral': RouteRecordInfo<'member-referral', '/member/referral', Record<never, never>, Record<never, never>>,
    'member-ticket': RouteRecordInfo<'member-ticket', '/member/ticket', Record<never, never>, Record<never, never>>,
    'member-ticket-id': RouteRecordInfo<'member-ticket-id', '/member/ticket/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'member-ticket-create': RouteRecordInfo<'member-ticket-create', '/member/ticket/create', Record<never, never>, Record<never, never>>,
    'member-withdrawals': RouteRecordInfo<'member-withdrawals', '/member/withdrawals', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
